<?php

namespace CollaborateurBundle\Repository;

/**
 * CollabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollabRepository extends \Doctrine\ORM\EntityRepository
{
}
